CREATE DATABASE IF NOT EXISTS panel_wa;
USE panel_wa;

CREATE TABLE pesanan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100),
  nomor VARCHAR(20),
  paket VARCHAR(50),
  tanggal DATETIME
);
